# Generated by Django 4.1.2 on 2022-11-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surNames', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('state', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('accessHour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.accesshours')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('companyPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypoint')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
