# Generated by Django 4.1.2 on 2022-11-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qrCode',
            field=models.ImageField(blank=True, upload_to='qrCode/'),
        ),
    ]
