# Generated by Django 4.1.2 on 2022-10-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(blank=True),
        ),
    ]
