# Generated by Django 4.1.2 on 2022-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_is_admin_alter_person_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
