# Generated by Django 4.1.2 on 2022-11-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_person_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='qrCode',
        ),
    ]
