# Generated by Django 4.1.2 on 2022-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_person_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(),
        ),
    ]
