# Generated by Django 4.1.2 on 2022-10-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_person_is_staff_remove_person_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
