# Generated by Django 4.1.2 on 2022-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_person_id_alter_person_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
    ]
