# Generated by Django 4.1.2 on 2022-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
