# Generated by Django 4.1.2 on 2022-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrres',
            name='district',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
