# Generated by Django 4.1.2 on 2022-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_address_alter_company_location'),
        ('core', '0003_rename_adrres_adrress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adrress',
            new_name='Address',
        ),
    ]
