# Generated by Django 4.1.2 on 2022-10-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_adrress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='deparment',
            new_name='department',
        ),
    ]
