# Generated by Django 4.1.2 on 2022-10-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypoint',
            old_name='status',
            new_name='state',
        ),
    ]
