# Generated by Django 4.1.2 on 2022-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_accesshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesshistory',
            name='checkOut',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
