# Generated by Django 4.1.2 on 2022-10-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_adrres_adrress'),
        ('company', '0003_rename_status_companypoint_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.adrress'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
