# Generated by Django 4.1.2 on 2022-10-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_address_alter_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='webSite',
            field=models.URLField(max_length=100),
        ),
    ]
