# Generated by Django 4.1.2 on 2022-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
