# Generated by Django 4.1.2 on 2022-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companypoint',
            name='geolocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
