# Generated by Django 4.1.2 on 2022-11-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_company_id_alter_company_nit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesshours',
            old_name='endtTime',
            new_name='endTime',
        ),
        migrations.AddField(
            model_name='accesshours',
            name='companyPoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companypoint'),
        ),
    ]
